name: Quick Testing

on:
  push:
    branches: main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Setup
      run: cargo run -p matla -- setup -o --standalone
    - name: Run Tests
      run: make test
